# -*- coding: utf-8 -*-
"""Descriptive_stats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kh9mFsu87rZ6sQF_wwNk6AntQmSDLl30
"""

import pandas as pd
import numpy as np
df = pd.read_csv("/content/Mall_Customers - Mall_Customers.csv")
df

df.mean()

df.loc[:,'Age'].mean()

df.mean(axis = 1)[0:4]

df.median()

df.loc[:,'Age'].median()

df.median(axis = 1)[0:4]

df.mode()

df.loc[:,'Age'].mode()

df.min()

df.loc[:,'Age'].min(skipna = False)

df.max()

df.loc[:,'Age'].max(skipna = False)

df.std()

df.loc[:,'Age'].std()

df.std(axis=1)[0:4]

df.groupby(['Genre'])['Age'].mean()

df_u=df.rename(columns= {'Annual Income (k$)':'Income'},inplace=False)
df_u

df_u.groupby(['Genre'])['Income'].mean()

from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()
enc_df = pd.DataFrame(enc.fit_transform(df[['Genre']]).toarray())
enc_df

df_encode =df_u.join(enc_df)
df_encode

iris = pd.read_csv("/content/IRIS - IRIS.csv")
iris

irisSet = (iris['species']== 'Iris-setosa')
print('Iris-setosa')
print(iris[irisSet].describe())
print()

irisVer = (iris['species']== 'Iris-versicolor')
print('Iris-versicolor')
print(iris[irisVer].describe())
print()

irisVir = (iris['species']== 'Iris-virginica')
print('Iris-virginica')
print(iris[irisVir].describe())

# iris[irisSet]
iris[irisVer]
# iris[irisVir]