# -*- coding: utf-8 -*-
"""DV3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1COqVSaRF7_PxSrVE2Ax6y33hhj7fVMm_
"""

import numpy as np
import pandas as pd
import seaborn as sns

df = sns.load_dataset("iris")
#df.columns = ["col1","col2","col3","col4","col5"]

df.head()

column = len(list(df))
column

"""1.List down the features and their types (e.g., numeric, nominal) available in the dataset."""

df.info()

"""Hence the dataset contains 4 numerical columns and 1 object column"""

np.unique(df["species"])

df.describe()

"""Compute and display summary statistics for each feature available in the dataset."""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline

"""Data Visualization-Create a histogram for each feature in the dataset to illustrate the feature distributions. Plot each histogram."""

fig, axes = plt.subplots(2, 2, figsize=(16, 8))


axes[0,0].set_title("Distribution of First Column")
axes[0,0].hist(df["sepal_length"]);

axes[0,1].set_title("Distribution of Second Column")
axes[0,1].hist(df["sepal_width"]);

axes[1,0].set_title("Distribution of Third Column")
axes[1,0].hist(df["petal_length"]);

axes[1,1].set_title("Distribution of Fourth Column")
axes[1,1].hist(df["petal_width"]);

data_to_plot = [df["sepal_length"],df["sepal_width"],df["petal_length"],df["petal_width"]]

sns.set_style("whitegrid")
# Creating a figure instance
fig = plt.figure(1, figsize=(12,8))

# Creating an axes instance
ax = fig.add_subplot(111)

# Creating the boxplot
bp = ax.boxplot(data_to_plot)

"""Create a boxplot for each feature in the dataset. All of the boxplots should be combined into a single plot. Compare distributions and identify outliers.



If we observe closely. for the box 2, interquartile distance is roughly around 0.75 hence the values lying beyond this range of (third quartile + interquartile distance) i.e. roughly around 4.05 will be considered as outliers. Similarly outliers with other boxplots can be found

ALTERNATIVE WAY
"""

print("\n\nThe features in the dataset are as follows : ")
print("1. Sepal length : ", df['sepal_length'].dtype)
print("2. Sepal width : ", df['sepal_width'].dtype)
print("3. Petal length : ", df['petal_length'].dtype)
print("4. Petal width : ", df['petal_width'].dtype)
print("5. Species : ", df['species'].dtype)

# sns.histplot(x = df['sepal_length'], kde=False)
# sns.histplot(x = df['sepal_width'], kde=True)
# sns.histplot(x = df['petal_length'], kde=True)
# sns.histplot(x = df['petal_width'], kde=True)


# sns.boxplot(df['sepal_length'])
# sns.boxplot(df['sepal_width'])
# sns.boxplot(df['petal_length'])
# sns.boxplot(df['petal_width'])


# sns.boxplot(x='sepal_length',y='species',data=df)
# sns.boxplot(x='petal_length',y='species',data=df)