# -*- coding: utf-8 -*-
"""DA1_Housing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SuFUOXxxs2CCJnQr1tHuomYRiTuKvjZE
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('/content/Housing - data4.csv')
#print(dataset)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

# Visualising the Training set results
plt.scatter(X_train, y_train, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Area vs Price (Training set)')
plt.xlabel('Area')
plt.ylabel('Price')
plt.show()

#Visualising the Test set results
plt.scatter(X_test, y_test, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Area vs Salary (Test set)')
plt.xlabel('Area')
plt.ylabel('Price')
plt.show()

print(regressor.predict([[14000000]]))

print(regressor.coef_)
print(regressor.intercept_)