# -*- coding: utf-8 -*-
"""DV1and2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BkvHxYtPvzPElsjpjtXvd354vqoCpylT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/titanic_data.csv')
data

data.shape

data.describe()

data.describe(include = 'object')

data.isnull().sum()

data['Age'] = data['Age'].fillna(np.mean(data['Age']))
print(data['Age'].fillna(np.mean(data['Age'])))

data['Cabin'] = data['Cabin'].fillna(data['Cabin'].mode()[0])
print(data['Cabin'].fillna(data['Cabin'].mode()[0]))

data['Embarked'] = data['Embarked'].fillna(data['Embarked'].mode()[0])

data.isnull().sum()

sns.distplot(data['Fare'])

sns.distplot(data['Fare'], kde=False)

sns.distplot(data['Fare'], kde=False, bins=10)

sns.jointplot(x='Age', y='Fare', data=data)

sns.pairplot(data)

sns.rugplot(data['Fare'])

sns.barplot(x='Sex', y='Fare', data=data)

sns.barplot(x='Sex', y='Age', data=data, estimator=np.std)

sns.catplot(x= 'Sex', y = 'Fare', data=data, kind = 'strip')

sns.catplot(x= 'Sex', y = 'Age', data=data, kind = 'strip')

sns.countplot(x='Fare', data=data)

sns.scatterplot(x = 'Fare', y = 'Pclass', hue = 'Survived', data = data)

sns.scatterplot(x = 'Survived', y = 'Fare', data = data)

sns.boxplot(x='Sex', y='Age', data=data)

sns.boxplot(x='Survived', y='Fare', data=data)

sns.boxplot(x='Sex', y='Age', data=data, hue="Survived")

tc = data.corr()
sns.heatmap(tc, cmap="YlGnBu")
plt.title('Correlation')

"""**Price of Ticket for each passenger is distributed**"""

sns.catplot(x='Pclass', y='Fare', data=data, kind='bar')

sns.stripplot(x='Sex', y='Age', data=data)

sns.histplot(data=data,x='Fare',y='Survived')

sns.violinplot(x='Sex', y='Age', data=data, hue='Survived')

"""DV II

"""

sns.boxplot(x='Survived', y='Fare', data=data)

sns.boxplot(x='Sex', y='Age', data=data)

sns.boxplot(x='Sex', y='Age', data=data)

sns.boxplot(x='Survived', y='Fare', data=data)